#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gifsicle
Version  : 1.92
Release  : 1
URL      : https://github.com/kohler/gifsicle/archive/v1.92.tar.gz
Source0  : https://github.com/kohler/gifsicle/archive/v1.92.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gifsicle-bin = %{version}-%{release}
Requires: gifsicle-license = %{version}-%{release}
Requires: gifsicle-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)

%description
![gifsicle-logo](https://raw.githubusercontent.com/kohler/gifsicle/master/logo.gif)

%package bin
Summary: bin components for the gifsicle package.
Group: Binaries
Requires: gifsicle-license = %{version}-%{release}

%description bin
bin components for the gifsicle package.


%package license
Summary: license components for the gifsicle package.
Group: Default

%description license
license components for the gifsicle package.


%package man
Summary: man components for the gifsicle package.
Group: Default

%description man
man components for the gifsicle package.


%prep
%setup -q -n gifsicle-1.92
cd %{_builddir}/gifsicle-1.92

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579294219
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1579294219
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gifsicle
cp %{_builddir}/gifsicle-1.92/COPYING %{buildroot}/usr/share/package-licenses/gifsicle/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gifdiff
/usr/bin/gifsicle
/usr/bin/gifview

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gifsicle/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gifdiff.1
/usr/share/man/man1/gifsicle.1
/usr/share/man/man1/gifview.1
